server:
    port: 5544
management:
    endpoints.web.exposure.include: 'health, prometheus, metrics'

spring:
    profiles.active: prod
    application:
        name: rpg
    datasource:
        url: jdbc:postgresql://localhost/postgres?ssl=false&loglevel=2
        driver-class-name: org.postgresql.Driver
        name: postgres
        username: username
        password: password
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            write-dates-as-timestamps: false
        time-zone: America/Sao_Paulo
        default-property-inclusion: NON_NULL

logging:
    level:
        '[org.springframework]': info
        '[com.tesch.rpg]': debug 

springdoc:
    swagger-ui:
        path: /swagger-ui/
